/**
 * SmartDailyPlan Component
 *
 * AI-powered daily plan component that displays focus blocks, quick wins,
 * meetings, and defer suggestions generated by the AI.
 * Uses Tailwind CSS v4 for styling.
 *
 * Requirements: 1.6, 1.7, 5.1, 5.5, 6.4, 8.4, 8.5
 */

import { useState, useEffect } from "react";
import { useDailyPlan } from "../../hooks/useDailyPlan";
import { REGENERATE_PLAN_EVENT } from "../../hooks/useKeyboardShortcuts";
import type { PlanTask, ItemFeedbackType } from "../../services/backend/plan";

interface SmartDailyPlanProps {
  onTaskComplete?: (taskId: string) => void;
  onTaskCreate?: (title: string) => void;
}

export function SmartDailyPlan({
  onTaskComplete,
  onTaskCreate: _onTaskCreate,
}: SmartDailyPlanProps) {
  void _onTaskCreate;
  const {
    plan,
    isLoading,
    isGenerating,
    error,
    regenerate,
    submitItemFeedback,
  } = useDailyPlan();

  // Listen for keyboard shortcut to regenerate plan (Cmd+R)
  useEffect(() => {
    const handleRegenerate = () => {
      if (!isGenerating) {
        regenerate();
      }
    };

    window.addEventListener(REGENERATE_PLAN_EVENT, handleRegenerate);
    return () =>
      window.removeEventListener(REGENERATE_PLAN_EVENT, handleRegenerate);
  }, [regenerate, isGenerating]);

  const formatSuggestedTime = (time?: string) => {
    if (!time) return null;

    // If already readable format, return as is
    if (/^\d{1,2}:\d{2}\s?(AM|PM|am|pm)?$/i.test(time)) {
      return time;
    }

    // Descriptive times
    if (/^(morning|afternoon|evening|noon|early|late)/i.test(time)) {
      return time.charAt(0).toUpperCase() + time.slice(1);
    }

    // Try ISO parse
    try {
      const date = new Date(time);
      if (!isNaN(date.getTime())) {
        return date.toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "2-digit",
          hour12: true,
        });
      }
    } catch {
      // Parsing failed
    }

    return time;
  };

  const getPriorityClasses = (priority: PlanTask["priority"]) => {
    switch (priority) {
      case "high":
        return "bg-destructive/20 text-destructive border-destructive/80";
      case "medium":
        return "bg-amber-500/20 text-amber-500 border-amber-500/20";
      case "low":
        return "bg-green-500/20 text-green-500 border-green-500/20";
      default:
        return "bg-muted text-muted-foreground";
    }
  };

  const getTypeIcon = (type: PlanTask["type"]) => {
    switch (type) {
      case "focus":
        return "🎯";
      case "task":
        return "✅";
      case "email":
        return "📧";
      case "meeting":
        return "📅";
      case "break":
        return "☕";
      default:
        return "📋";
    }
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] gap-4 text-muted-foreground">
        <div className="w-8 h-8 border-4 border-muted/30 border-t-primary rounded-full animate-spin" />
        <p>Loading your AI-powered plan...</p>
      </div>
    );
  }

  if (error && !plan) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] gap-4 text-muted-foreground">
        <p className="text-destructive">{error}</p>
        <button
          onClick={regenerate}
          className="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-colors"
        >
          Generate Plan
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Summary Card */}
      {plan && (plan.summary || plan.energy_tip) && (
        <section className="p-5 rounded-2xl bg-gradient-to-br from-primary/10 to-purple-500/10 border-2 border-border/50 backdrop-blur-3xl shadow-xl shadow-primary/5">
          {plan.summary && (
            <p className="text-foreground/90 leading-relaxed mb-4 text-base">
              {plan.summary}
            </p>
          )}
          {plan.energy_tip && (
            <div className="flex items-start gap-3 p-3 rounded-xl bg-card/20 text-sm text-foreground/80 border border-border/30">
              <span className="text-lg">💡</span>
              <span className="leading-snug pt-0.5">{plan.energy_tip}</span>
            </div>
          )}
        </section>
      )}

      {/* Focus Blocks */}
      <Section
        title="Focus Blocks"
        icon="🎯"
        count={plan?.focus_blocks?.length ?? 0}
      >
        {!plan || plan.focus_blocks.length === 0 ? (
          <EmptyState>No focus blocks scheduled</EmptyState>
        ) : (
          <div className="space-y-3">
            {plan.focus_blocks.map((task) => (
              <TaskCard
                key={task.id}
                task={task}
                itemType="focus_block"
                onComplete={onTaskComplete}
                onFeedback={submitItemFeedback}
                formatTime={formatSuggestedTime}
                getPriorityClasses={getPriorityClasses}
                getTypeIcon={getTypeIcon}
              />
            ))}
          </div>
        )}
      </Section>

      {/* Quick Wins */}
      <Section
        title="Quick Wins"
        icon="⚡"
        count={plan?.quick_wins?.length ?? 0}
      >
        {!plan || plan.quick_wins.length === 0 ? (
          <EmptyState>No quick wins available</EmptyState>
        ) : (
          <div className="space-y-3">
            {plan.quick_wins.map((task) => (
              <TaskCard
                key={task.id}
                task={task}
                itemType="quick_win"
                onComplete={onTaskComplete}
                onFeedback={submitItemFeedback}
                formatTime={formatSuggestedTime}
                getPriorityClasses={getPriorityClasses}
                getTypeIcon={getTypeIcon}
              />
            ))}
          </div>
        )}
      </Section>

      {/* Meetings */}
      <Section title="Meetings" icon="📅" count={plan?.meetings?.length ?? 0}>
        {!plan || plan.meetings.length === 0 ? (
          <EmptyState>No meetings scheduled</EmptyState>
        ) : (
          <div className="space-y-3">
            {plan.meetings.map((meeting) => (
              <MeetingCard
                key={meeting.id}
                meeting={meeting}
                onFeedback={submitItemFeedback}
                formatTime={formatSuggestedTime}
              />
            ))}
          </div>
        )}
      </Section>

      {/* Defer Suggestions */}
      {plan && plan.defer_suggestions.length > 0 && (
        <Section
          title="Consider Deferring"
          icon="📌"
          count={plan.defer_suggestions.length}
        >
          <div className="space-y-2">
            {plan.defer_suggestions.map((suggestion, index) => (
              <DeferCard
                key={index}
                suggestion={suggestion}
                index={index}
                onFeedback={submitItemFeedback}
              />
            ))}
          </div>
        </Section>
      )}

      {/* No Plan State */}
      {!plan && !error && (
        <section className="p-12 rounded-2xl bg-card/10 border-2 border-border/30 backdrop-blur-2xl text-center shadow-xl">
          <p className="text-muted-foreground mb-6 text-lg">
            No plan generated yet for today.
          </p>
          <button
            onClick={regenerate}
            disabled={isGenerating}
            className="px-8 py-3 bg-primary text-primary-foreground rounded-xl font-medium
                         hover:bg-primary/90 transition-all disabled:opacity-50 shadow-lg shadow-primary/20"
          >
            {isGenerating ? "Generating..." : "Generate AI Plan"}
          </button>
        </section>
      )}
    </div>
  );
}

// Section Component
function Section({
  title,
  icon,
  count,
  children,
}: {
  title: string;
  icon: string;
  count: number;
  children: React.ReactNode;
}) {
  return (
    <section className="p-5 rounded-2xl mica-blur-vibrant border-2 border-border/50 shadow-xl shadow-primary/5 transition-all">
      <h2 className="flex items-center gap-3 text-lg font-semibold text-foreground mb-4 opacity-90">
        <span className="text-2xl filter drop-shadow-sm">{icon}</span>
        {title}
        {count > 0 && (
          <span className="ml-auto text-xs font-semibold text-muted-foreground bg-muted/20 border-2 border-border/10 px-2.5 py-1 rounded-full backdrop-blur-md">
            {count}
          </span>
        )}
      </h2>
      {children}
    </section>
  );
}

// Empty State
function EmptyState({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-center text-muted-foreground text-sm py-4">{children}</p>
  );
}

// Task Card
interface TaskCardProps {
  task: PlanTask;
  itemType: "focus_block" | "quick_win" | "meeting" | "defer";
  onComplete?: (taskId: string) => void;
  onFeedback?: (
    itemId: string,
    itemTitle: string,
    feedbackType: ItemFeedbackType,
    itemType: "focus_block" | "quick_win" | "meeting" | "defer"
  ) => Promise<boolean>;
  formatTime: (time?: string) => string | null;
  getPriorityClasses: (priority: PlanTask["priority"]) => string;
  getTypeIcon: (type: PlanTask["type"]) => string;
}

function TaskCard({
  task,
  itemType,
  onComplete,
  onFeedback,
  formatTime,
  getPriorityClasses,
  getTypeIcon,
}: TaskCardProps) {
  const [feedbackGiven, setFeedbackGiven] = useState<ItemFeedbackType | null>(
    null
  );
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleComplete = () => {
    if (task.source_id && onComplete) {
      onComplete(task.source_id);
    }
  };

  const handleFeedback = async (type: ItemFeedbackType) => {
    if (!onFeedback || isSubmitting) return;

    setIsSubmitting(true);
    const success = await onFeedback(task.id, task.title, type, itemType);
    if (success) {
      setFeedbackGiven(type);
    }
    setIsSubmitting(false);
  };

  return (
    <div className="flex items-start gap-4 p-4 rounded-xl bg-card/10 hover:bg-card/20 border border-transparent hover:border-border/60 transition-all duration-300 group">
      {task.source_type === "task" && (
        <input
          type="checkbox"
          onChange={handleComplete}
          className="mt-1 w-4 h-4 rounded-md border-muted-foreground/40 accent-primary focus:ring-primary/20"
          title="Mark as complete"
        />
      )}
      <div className="flex-1 min-w-0">
        <div className="flex flex-wrap items-center gap-2 mb-1.5">
          <span className="filter drop-shadow-sm opacity-90">
            {getTypeIcon(task.type)}
          </span>
          <span className="text-foreground font-medium text-base tracking-tight">
            {task.title}
          </span>
          <span
            className={`text-[10px] px-2 py-0.5 rounded-full uppercase border font-bold tracking-wider ${getPriorityClasses(
              task.priority
            )}`}
          >
            {task.priority}
          </span>
        </div>
        <div className="flex flex-wrap items-center gap-4 text-xs text-muted-foreground/80 font-medium">
          {formatTime(task.suggested_time) && (
            <span className="flex items-center gap-1.5">
              <span>🕐</span>
              {formatTime(task.suggested_time)}
            </span>
          )}
          {task.duration_minutes > 0 && (
            <span className="flex items-center gap-1.5">
              <span>⏱️</span>
              {task.duration_minutes}min
            </span>
          )}
        </div>
        {task.context && (
          <p className="mt-2 text-sm text-foreground/60 italic leading-relaxed">
            {task.context}
          </p>
        )}
      </div>
      <FeedbackButtons
        feedbackGiven={feedbackGiven}
        isSubmitting={isSubmitting}
        onFeedback={handleFeedback}
      />
    </div>
  );
}

// Meeting Card
interface MeetingCardProps {
  meeting: PlanTask;
  onFeedback?: (
    itemId: string,
    itemTitle: string,
    feedbackType: ItemFeedbackType,
    itemType: "focus_block" | "quick_win" | "meeting" | "defer"
  ) => Promise<boolean>;
  formatTime: (time?: string) => string | null;
}

function MeetingCard({ meeting, onFeedback, formatTime }: MeetingCardProps) {
  const [feedbackGiven, setFeedbackGiven] = useState<ItemFeedbackType | null>(
    null
  );
  const [isSubmitting, setIsSubmitting] = useState(false);

  const isStartingSoon = () => {
    if (!meeting.suggested_time) return false;
    try {
      const meetingTime = new Date(meeting.suggested_time);
      const now = new Date();
      const diffMinutes = (meetingTime.getTime() - now.getTime()) / (1000 * 60);
      return diffMinutes >= 0 && diffMinutes <= 15;
    } catch {
      return false;
    }
  };

  const handleFeedback = async (type: ItemFeedbackType) => {
    if (!onFeedback || isSubmitting) return;

    setIsSubmitting(true);
    const success = await onFeedback(
      meeting.id,
      meeting.title,
      type,
      "meeting"
    );
    if (success) {
      setFeedbackGiven(type);
    }
    setIsSubmitting(false);
  };

  return (
    <div
      className={`flex items-start gap-4 p-4 rounded-xl transition-all border
                    ${
                      isStartingSoon()
                        ? "bg-primary/10 border-primary shadow-lg shadow-primary/10"
                        : "bg-card/10 hover:bg-card/20 border-transparent hover:border-border/60"
                    }`}
    >
      <div className="text-primary text-sm font-semibold min-w-[70px] uppercase tracking-wide">
        {formatTime(meeting.suggested_time) || "TBD"}
      </div>
      <div className="flex-1 min-w-0">
        <span className="text-foreground font-medium text-base tracking-tight block">
          {meeting.title}
        </span>
        {meeting.duration_minutes > 0 && (
          <span className="inline-block mt-1 text-xs text-muted-foreground font-medium bg-muted/20 px-2 py-0.5 rounded-md">
            {meeting.duration_minutes} min
          </span>
        )}
        {meeting.context && (
          <p className="text-sm text-foreground/60 mt-1.5 leading-relaxed">
            {meeting.context}
          </p>
        )}
      </div>
      <FeedbackButtons
        feedbackGiven={feedbackGiven}
        isSubmitting={isSubmitting}
        onFeedback={handleFeedback}
      />
    </div>
  );
}

// Defer Card
interface DeferCardProps {
  suggestion: string | PlanTask;
  index: number;
  onFeedback?: (
    itemId: string,
    itemTitle: string,
    feedbackType: ItemFeedbackType,
    itemType: "focus_block" | "quick_win" | "meeting" | "defer"
  ) => Promise<boolean>;
}

function DeferCard({ suggestion, index, onFeedback }: DeferCardProps) {
  const [feedbackGiven, setFeedbackGiven] = useState<ItemFeedbackType | null>(
    null
  );
  const [isSubmitting, setIsSubmitting] = useState(false);

  const suggestionText =
    typeof suggestion === "string" ? suggestion : suggestion.title;
  const suggestionId =
    typeof suggestion === "string" ? `defer-${index}` : suggestion.id;

  const handleFeedback = async (type: ItemFeedbackType) => {
    if (!onFeedback || isSubmitting) return;

    setIsSubmitting(true);
    const success = await onFeedback(
      suggestionId,
      suggestionText,
      type,
      "defer"
    );
    if (success) {
      setFeedbackGiven(type);
    }
    setIsSubmitting(false);
  };

  return (
    <div className="flex items-center gap-2 p-2 rounded-lg bg-card/30 border-l-2 border-muted-foreground/30">
      <span className="flex-1 text-sm text-muted-foreground">
        {suggestionText}
      </span>
      <FeedbackButtons
        feedbackGiven={feedbackGiven}
        isSubmitting={isSubmitting}
        onFeedback={handleFeedback}
      />
    </div>
  );
}

// Feedback Buttons
interface FeedbackButtonsProps {
  feedbackGiven: ItemFeedbackType | null;
  isSubmitting: boolean;
  onFeedback: (type: ItemFeedbackType) => void;
}

function FeedbackButtons({
  feedbackGiven,
  isSubmitting,
  onFeedback,
}: FeedbackButtonsProps) {
  return (
    <div className="flex gap-1 flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
      <button
        className={`p-1.5 rounded transition-colors ${
          feedbackGiven === "positive"
            ? "bg-green-500/10 text-green-500"
            : "text-muted-foreground hover:text-foreground hover:bg-muted"
        }`}
        onClick={() => onFeedback("positive")}
        disabled={isSubmitting || feedbackGiven !== null}
        title="Helpful"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
        >
          <path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3" />
        </svg>
      </button>
      <button
        className={`p-1.5 rounded transition-colors ${
          feedbackGiven === "negative"
            ? "bg-destructive/10 text-destructive"
            : "text-muted-foreground hover:text-foreground hover:bg-muted"
        }`}
        onClick={() => onFeedback("negative")}
        disabled={isSubmitting || feedbackGiven !== null}
        title="Not helpful"
      >
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
        >
          <path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17" />
        </svg>
      </button>
    </div>
  );
}
